annotations:
  artifacthub.io/changes: |
    - kind: added
      description: "Allow custom ClusterRole rules to be specified for sources without defaults."
    - kind: changed
      description: "Update ExternalDNS version to v0.10.2."
    - kind: changed
      description: "Set ClusterRole rules based more enabled sources."
apiVersion: v2
appVersion: 0.10.2
description: ExternalDNS synchronizes exposed Kubernetes Services and Ingresses with
  DNS providers.
home: https://github.com/kubernetes-sigs/external-dns/
icon: https://github.com/kubernetes-sigs/external-dns/raw/master/img/external-dns.png
keywords:
- kubernetes
- external-dns
- dns
maintainers:
- email: steve.hipwell@gmail.com
  name: stevehipwell
name: external-dns
sources:
- https://github.com/kubernetes-sigs/external-dns/
type: application
version: 1.7.1
